/**
 * Even Fibonacci numbers
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */

class Problem2{
    fun solve(paramNum: Int): Long {
        var firstNum = 0
        var secondNum = 1
        var temp: Int
        var evenSum: Long = 0

        while (evenSum < paramNum){
            temp = secondNum
            secondNum += firstNum
            firstNum = temp

            if(secondNum%2 == 0){
                evenSum += secondNum
            }
        }

        return evenSum
    }
}